from typing import Protocol


class BanterPhrasePort(Protocol):
    """Outbound port for fetching and adding banter phrases, scoped per chat."""

    async def get_random_insult(self, chat_id: int) -> str: ...

    async def get_random_compliment(self, chat_id: int) -> str: ...

    async def add_insult(self, chat_id: int, phrase: str) -> None: ...

    async def add_compliment(self, chat_id: int, phrase: str) -> None: ...
