# Point thresholds -> level label, evaluated from highest to lowest.
# NOTE: labels stay in Spanish on purpose - they're user-facing copy for the group.
LEVEL_THRESHOLDS: list[tuple[int, str]] = [
    (15000, "Entidad cósmica del espectro. Solo baja a corregir gente"),
    (12000, "Ha internalizado el DSM-5 y lo usa en conversaciones"),
    (10000, "El algoritmo de YouTube le reza para que no lo rompa"),
    (9000,  "Sistema de archivos mental con permisos root"),
    (7500,  "Tiene su propio RFC y nadie lo rechazó"),
    (6500,  "Corrige papers académicos en los comentarios"),
    (5000,  "Wikipedia andante con fuentes inventadas"),
    (4500,  "Explica un tema durante 4 horas sin notar el tiempo"),
    (4000,  "Corrige a los mods del subreddit mientras duermen"),
    (3500,  "Su historial de búsqueda le da miedo a Google"),
    (3000,  "Su historial de Google es material universitario"),
    (2700,  "Obsidian con 2400 notas de un solo tema"),
    (2500,  "Se sabe el lore que ni el creador recuerda"),
    (2200,  "Documento de 60 páginas para demostrar que todos están mal"),
    (2000,  "PowerPoint de 87 diapositivas explicando por qué todos fallan"),
    (1800,  "Se ofende cuando simplifican su tema favorito"),
    (1500,  "Su personalidad completa se basa en un solo tópico"),
    (1350,  "Creó un framework mental y se molesta si no lo usan"),
    (1200,  "Ensayos de 4000 palabras en comentarios de Facebook"),
    (1100,  "Reglas internas no negociables sobre su interés"),
    (1000,  "Corrige a la familia en WhatsApp con fuentes"),
    (900,   "Se disocia si alguien dice algo técnicamente incorrecto"),
    (800,   "Carpetas dentro de carpetas con sistema de nombres"),
    (700,   "Reorganiza bibliotecas ajenas porque 'estaban mal'"),
    (600,   "Se enoja si usan mal un término técnico"),
    (550,   "Hiperfocaliza a mitad de una charla y no puede parar"),
    (500,   "Explica el meme tres veces porque 'estaba mal contado'"),
    (450,   "Sistema de colores y etiquetas para clasificar gente"),
    (400,   "Opinión extrema sobre el orden de las carpetas"),
    (350,   "Corrige cómo otros organizan sus archivos"),
    (300,   "Ha perdido amigos por discusiones de versionado"),
    (270,   "Se toma como ataque personal si no siguen 'la forma correcta'"),
    (250,   "Suelta lore inútil sin que nadie lo pida"),
    (220,   "Monólogos internos de 20 minutos sobre detalles"),
    (200,   "Empieza frases con 'técnicamente…' sin que pregunten"),
    (180,   "Se frustra si no entienden su explicación a la primera"),
    (150,   "Admin de Discord con más reglas que usuarios"),
    (130,   "Roles y permisos excesivamente específicos"),
    (120,   "Sistema de tags mental para clasificar personas"),
    (110,   "Se siente mal cuando rompen sus reglas no dichas"),
    (100,   "Corrige pronunciación en inglés aunque hablen español"),
    (90,    "Repite la misma corrección varias veces"),
    (80,    "Se le escapa un 'en realidad…' varias veces por charla"),
    (70,    "No puede dejar un tema hasta que quede 'correcto'"),
    (60,    "Opinión muy elaborada sobre por qué cierta distro es superior"),
    (55,    "Mete discusiones técnicas en contextos sociales"),
    (50,    "Explica el meme antes de que se lo pidan"),
    (45,    "Necesita que las cosas estén 'bien explicadas'"),
    (40,    "Ha dicho 'eso no es así' en una reunión familiar"),
    (35,    "Revisa mentalmente conversaciones horas después"),
    (30,    "Se sabe atajos de programas que casi no usa"),
    (25,    "Carpeta 'cosas importantes' con 300 archivos random"),
    (22,    "Organiza cosas que nadie le pidió organizar"),
    (20,    "Corrige ortografía en el grupo a las 2 a.m."),
    (17,    "Se incomoda cuando las cosas no siguen orden lógico"),
    (15,    "Empieza con 'no es por ser intenso, pero…'"),
    (12,    "Pequeños rituales mentales antes de tareas simples"),
    (10,    "Se le escapa un 'en realidad…' de vez en cuando"),
    (8,     "Se traba porque necesita decirlo 'de la forma correcta'"),
    (7,     "Opiniones firmes sobre temas que nadie discute"),
    (5,     "Se emociona demasiado explicando algo random"),
    (4,     "Nota patrones que el resto ignora por completo"),
    (3,     "Neurotípico con sospechas razonables"),
    (2,     "Todavía puede pasar por normal la mayoría del tiempo"),
    (1,     "Neurotípico sospechoso"),
    (0,     "Increíblemente, una persona normal"),
]

DEFAULT_RANKING_LIMIT = 10
