# NOTE: timezone the group operates in, used to compute "today" so the daily
# reading flips at local midnight instead of UTC midnight.
TIMEZONE = "America/Bogota"

# NOTE: Spanish sign names - user-facing copy, also used as the values accepted
# by the /horoscopo command argument.
VALID_SIGNS = [
    "aries",
    "tauro",
    "geminis",
    "cancer",
    "leo",
    "virgo",
    "libra",
    "escorpio",
    "sagitario",
    "capricornio",
    "acuario",
    "piscis",
]

LUCKY_COLORS = [
    "verde terminal",
    "azul pantalla de la muerte",
    "negro consola",
    "amarillo warning",
    "rojo error 500",
    "morado dark mode",
    "gris kernel panic",
    "naranja soldadura fría",
    "blanco whitespace",
    "cian syntax highlight",

    "rojo sangre de merge conflict",
    "azul profundo de un segfault",
    "verde fosforescente de matriz",
    "amarillo post-it de TODO eterno",
    "naranja herrumbre de servidor olvidado",
    "violeta de pantalla quemada",
    "rosa chicle de código legacy",
    "turquesa de cable ethernet barato",
    "beige de gabinete viejo",
    "marrón de café derramado en el teclado",
    "dorado de commit que por fin pasó el CI",
    "plateado de chasis abierto a las 3 a.m.",
    "indigo de terminal con tema gruvbox",
    "magenta de error de sintaxis brillante",
    "coral de LED de disco duro muriendo",
    "lavanda de fondo de VS Code a las 4 a.m.",
    "oliva de camuflaje de sysadmin",
    "carmesí de alerta de monitoreo",
    "celeste de cielo visto por última vez hace meses",
    "grafito de laptop sin pegatinas",
    "salomé de logs que nadie lee",
    "esmeralda de uptime perfecto",
    "ámbar de warning ignorado",
    "púrpura imperial de root",
    "ocre de documentación desactualizada",

    "rosa chicle de prepucio iluminado",
    "marrón chocolate de anomancia profunda",
    "beige arena de nalgas al sol",
    "rojo inflamado de ojete post-fiesta",
    "negro abismo de culo sin fondo",
    "rosado tierno de ano en modo read-only",
    "marrón oscuro de rumpología avanzada",
    "piel canela de trasero bien cacheado",

    "gris depresión funcional",
    "negro vacío de anhedonia",
    "amarillo manía a las 3 a.m.",
    "azul frío de disociación",
    "rojo alerta de crisis de pánico",
    "violeta de pensamientos intrusivos",
    "verde enfermo de ansiedad anticipatoria",
    "blanco clínico de internación mental",
]


MOODS = [
    "en modo debug existencial",
    "con hambre de uptime",
    "paranoico por un CVE",
    "eufórico porque compiló a la primera",
    "resignado ante un merge conflict",
    "en negación sobre sus backups",
    "con el ego de un sudoer",
    "nostálgico de cuando internet andaba con módem",
    "ansioso esperando el CI",
    "zen, como root en producción sin miedo",

    "con el alma en modo immutable",
    "listo para hacer force push a la realidad",
    "en estado de race condition emocional",
    "compilando sentimientos con -Wall -Werror",
    "esperando que el kernel de la vida no haga panic",
    "con permisos de solo lectura en el corazón",
    "haciendo strace a sus propias decisiones",
    "en rolling release de crisis existenciales",
    "documentando su dolor en formato man page",
    "con el corazón en LTS: estable pero sin features nuevas",

    "en pleno episodio de hiperfocalización inútil",
    "disociado pero todavía respondiendo tickets",
    "con ansiedad de rendimiento a nivel kernel",
    "maníaco productivo hasta que se le acabe la dopamina",
    "en modo TOC reorganizando emociones ajenas",
    "deprimido funcional con uptime engañoso",
    "teniendo un soft lockup de overthinking",
    "con pensamientos intrusivos en background",
    "en crisis pero con buenos logs",
    "resignado a su propio segmentation fault emocional",

    "con el culo en modo read-only por precaución",
    "sintiendo la rumpología del día en la lumbar",
    "con el ano en estado de race condition",
    "hiperfocalizado en la geometría de un trasero lejano",
    "con el prepucio en modo copyleft: libre pero con reglas",
    "detectando vulnerabilidades en ojete propio y ajeno",
    "en estado de buffer overflow de deseo",
    "con el trasero estable como Debian y el resto en llamas",
    "haciendo debugging profundo de su propia anomancia",
    "con el culo cacheado y el corazón en swap",

    "listo para corregir el orden de las carpetas del universo",
    "con ganas de reorganizar la vida de alguien sin que se lo pidan",
    "explicando un meme tres veces porque 'estaba mal contado'",
    "sintiendo que su existencia es un ticket de soporte sin prioridad",
    "en modo 'técnicamente hablando...' permanente",
    "con el ego de quien tiene un RFC propio",
    "esperando que alguien por fin lea su documentación emocional",
    "en negación sobre el estado de su /home emocional",
    "con hambre de un merge conflict bien resuelto",
    "zen solo porque ya no le quedan tears que derramar",
]


LUCKY_TIMES = [
    "3:14 AM (hora de deploys arriesgados)",
    "9:00 AM (daily standup)",
    "12:00 PM (cronjob de mediodía)",
    "4:04 PM (404 de la tarde)",
    "6:66 PM (hora inexistente, como tu documentación)",
    "11:59 PM (justo antes del deadline)",
    "1:23 AM (debugging nocturno)",
    "8:08 AM (backup automático)",
    "2:22 PM (siesta post-almuerzo)",
    "10:10 PM (hora de romper el ambiente de staging)",

    "3:33 AM (hora del tercer kernel panic del día)",
    "4:20 AM (hora de contemplar el vacío y el uptime)",
    "5:00 AM (cuando el CI finalmente termina)",
    "7:77 AM (hora imposible, como tu work-life balance)",
    "11:11 AM (hora de pedir un deseo al servidor)",
    "1:11 PM (hora de almorzar mirando logs)",
    "3:33 PM (hora de la crisis de la tarde)",
    "5:55 PM (hora de fingir que el día fue productivo)",
    "9:99 PM (hora que no existe, como tu documentación)",
    "2:47 AM (hora exacta del soft lockup emocional)",

    "3:17 AM (hora clásica de pensamientos intrusivos)",
    "4:04 AM (hora de la disociación nocturna)",
    "5:55 AM (hora en que la ansiedad madruga antes que vos)",
    "2:22 AM (hora de revisar conversaciones de hace tres días)",
    "1:01 AM (hora de renegociar con tu propio cerebro)",

    "3:69 AM (hora de la rumpología profunda)",
    "4:20 PM (hora de analizar la geometría de un trasero)",
    "2:34 AM (hora en que el ano entra en modo debug)",
    "6:09 PM (hora de checkear el estado del prepucio)",
    "11:34 PM (hora de la anomancia nocturna)",

    "3:00 AM (hora en que el universo te obliga a reorganizar carpetas)",
    "4:44 AM (hora de escribir un monólogo sobre por qué tu distro es superior)",
    "12:34 AM (hora de corregir a alguien en un grupo dormido)",
    "2:56 AM (hora del merge conflict entre libido y sueño)",
    "5:18 AM (hora en que aceptás que hoy tampoco vas a tocar pasto)",
]

LUCKY_NUMBER_MIN = 0
LUCKY_NUMBER_MAX = 127
